version: '3.1'

services:
  adminer:
    image: adminer:latest
    restart: always
    ports: 
      - 3001:8080
  db:
    image: postgres:15
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data